In [1]:
import numpy as np

In [2]:
arr = np.arange(start=1, stop=9, step=1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr = np.arange(start=1, stop=10, step=1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.arange(start=1, stop=9, step=0.5)
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5])

In [6]:
arr = np.arange(start=1, stop=9, step=2)
arr

array([1, 3, 5, 7])

In [7]:
arr = np.arange(start=1, stop=9, step=3)
arr

array([1, 4, 7])

In [10]:
arr = np.zeros(shape=(2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr = np.zeros(shape=(3,2,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
arr = np.ones(shape=(2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
arr = np.linspace(start=1, stop=5, num=9)
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [16]:
arr = np.linspace(start=10, stop=50, num=10)
arr

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [17]:
arr = np.linspace(start=-3, stop=5, num=9)
arr

array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [19]:
arr = np.random.rand(3,4,2)
arr

array([[[0.18549598, 0.11831079],
        [0.45409314, 0.29901578],
        [0.58203995, 0.0762331 ],
        [0.99423854, 0.35410343]],

       [[0.82588851, 0.06532186],
        [0.22858511, 0.2934068 ],
        [0.65520047, 0.14227886],
        [0.49489087, 0.73794731]],

       [[0.65905526, 0.51643816],
        [0.18112575, 0.25751908],
        [0.19287632, 0.63692017],
        [0.17569673, 0.74030375]]])

In [20]:
arr = np.random.randn(8, 2)
arr

array([[-0.60501688, -0.9862019 ],
       [-1.16710801, -1.36161744],
       [ 0.56280432, -0.35993119],
       [ 0.496882  ,  1.96758518],
       [ 1.20468687, -1.57748442],
       [-1.59193709,  0.06349618],
       [ 0.52176767, -0.4178305 ],
       [ 0.58325703, -0.7421921 ]])

In [21]:
arr = np.random.randn(25)
arr

array([-0.44327705,  0.61504761,  1.02402312, -1.61247144, -0.92347317,
        2.96063301, -0.34197556, -1.12549516, -0.52214651,  0.66454405,
        1.05727845, -1.12335191,  0.92081476,  0.3325665 , -0.61545142,
        0.63465132, -0.70899188,  2.72801542,  1.37707061, -1.19093495,
       -0.0757505 , -0.17625113,  1.00579864,  1.82888121,  0.14615522])

In [22]:
arr = np.random.randint(low=10, high=50, size=5) # 1-d array, shape: 5 elements
arr

array([20, 27, 24, 45, 13])

In [23]:
arr = np.random.randint(low=250, high=888, size=(4, 3)) # 2-d array, shape: 4 rows x 3 columns
arr

array([[301, 670, 645],
       [275, 768, 470],
       [385, 862, 452],
       [665, 260, 763]])

In [24]:
arr = np.random.randint(low=250, high=888, size=(4, 5)) # 2-d array, shape: 4 rows x 5 columns
arr

array([[705, 842, 721, 518, 626],
       [320, 791, 783, 568, 567],
       [734, 321, 366, 329, 267],
       [545, 358, 406, 680, 625]])

In [ ]:
arr = np.random.randint(low=250, high=888, size=(2, 3, 2)) # 3-d array, shape: 3 rows x 2 columns
arr

array([[[562, 710],
        [647, 858],
        [835, 311]],

       [[258, 479],
        [344, 621],
        [666, 557]]])

In [36]:
np.random.seed(seed=10)
arr = np.random.randint(low=10,high=50,size=5)
arr

array([19, 46, 25, 10, 38])