In [1]:
import numpy as np

In [2]:
np.random.seed(seed=10)
arr = np.random.randint(low=1,high=25, size=(3,5))
arr

array([[10,  5, 16,  1, 18],
       [17, 18,  9, 10,  1],
       [11,  9, 23,  5, 20]])

In [ ]:
arr>4 # Boolean array where True indicates elements greater than 4

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [4]:
arr[arr>4] # Accessing elements greater than 4

array([10,  5, 16, 18, 17, 18,  9, 10, 11,  9, 23,  5, 20])

In [5]:
arr[arr<7] # Accessing elements less than 7

array([5, 1, 1, 5])

In [6]:
arr[(arr>4) & (arr<=17)] # Accessing elements greater than 4 and less than or equal to 17

array([10,  5, 16, 17,  9, 10, 11,  9,  5])

In [7]:
arr[(arr<=5) | (arr>15)] # Accessing elements less than or equal to 5 or greater than 15

array([ 5, 16,  1, 18, 17, 18,  1, 23,  5, 20])

In [8]:
arr[((arr<=2) | (arr>18)) | (arr==9)] # Accessing elements less than or equal to 2, greater than 18, or equal to 9

array([ 1,  9,  1,  9, 23, 20])

In [9]:
macro_arr=np.array([[0.9,0.1],[2.1,0.1],[2.7,0.1],[4.4,0.25],[5.5,0.625],[7.9,1.125],[8.7,2],[9.4,3.25]])
macro_arr

array([[0.9  , 0.1  ],
       [2.1  , 0.1  ],
       [2.7  , 0.1  ],
       [4.4  , 0.25 ],
       [5.5  , 0.625],
       [7.9  , 1.125],
       [8.7  , 2.   ],
       [9.4  , 3.25 ]])

In [10]:
macro_arr[(macro_arr<=1) | (macro_arr>9)] # Accessing elements less than or equal to 1 or greater than 9

array([0.9  , 0.1  , 0.1  , 0.1  , 0.25 , 0.625, 9.4  ])