In [1]:
import numpy as np

In [2]:
# Create a NumPy array from the same Python list and assign it to variable a
a = np.array([2,3,4])
# Multiply the variable by 3
a * 3

array([ 6,  9, 12])

In [4]:
np.random.seed(seed=2)
arr1 = np.random.randint(low=0, high=8, size=(3,5))
arr1

array([[0, 7, 5, 0, 6],
       [3, 2, 3, 0, 7],
       [2, 1, 7, 3, 5]])

In [5]:
np.random.seed(seed=1)
arr2 = np.random.randint(low=0, high=50, size=(3,5))
arr2

array([[37, 43, 12,  8,  9],
       [11,  5, 15,  0, 16],
       [ 1, 12,  7, 45,  6]])

In [7]:
arr2 + 2

array([[39, 45, 14, 10, 11],
       [13,  7, 17,  2, 18],
       [ 3, 14,  9, 47,  8]])

In [8]:
arr1 / 7

array([[0.        , 1.        , 0.71428571, 0.        , 0.85714286],
       [0.42857143, 0.28571429, 0.42857143, 0.        , 1.        ],
       [0.28571429, 0.14285714, 1.        , 0.42857143, 0.71428571]])

In [9]:
arr1 * .75

array([[0.  , 5.25, 3.75, 0.  , 4.5 ],
       [2.25, 1.5 , 2.25, 0.  , 5.25],
       [1.5 , 0.75, 5.25, 2.25, 3.75]])

In [11]:
arr1 - 3

array([[-3,  4,  2, -3,  3],
       [ 0, -1,  0, -3,  4],
       [-1, -2,  4,  0,  2]])

In [12]:
arr1 ** 3

array([[  0, 343, 125,   0, 216],
       [ 27,   8,  27,   0, 343],
       [  8,   1, 343,  27, 125]])

In [13]:
arr1 ** 2

array([[ 0, 49, 25,  0, 36],
       [ 9,  4,  9,  0, 49],
       [ 4,  1, 49,  9, 25]])

In [14]:
arr1 + arr2  # Adding two arrays of the same shape

array([[37, 50, 17,  8, 15],
       [14,  7, 18,  0, 23],
       [ 3, 13, 14, 48, 11]])

In [15]:
arr1 * arr2

array([[  0, 301,  60,   0,  54],
       [ 33,  10,  45,   0, 112],
       [  2,  12,  49, 135,  30]])

In [16]:
arr2 - arr1

array([[37, 36,  7,  8,  3],
       [ 8,  3, 12,  0,  9],
       [-1, 11,  0, 42,  1]])

In [17]:
arr1 /  arr2

/var/folders/yn/4hm9bbfn0414pdpdfbn4x7sh0000gn/T/ipykernel_22289/1158826047.py:1: RuntimeWarning: invalid value encountered in divide
  arr1 /  arr2


array([[0.        , 0.1627907 , 0.41666667, 0.        , 0.66666667],
       [0.27272727, 0.4       , 0.2       ,        nan, 0.4375    ],
       [2.        , 0.08333333, 1.        , 0.06666667, 0.83333333]])

In [18]:
1 / arr2

/var/folders/yn/4hm9bbfn0414pdpdfbn4x7sh0000gn/T/ipykernel_22289/3854864060.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr2


array([[0.02702703, 0.02325581, 0.08333333, 0.125     , 0.11111111],
       [0.09090909, 0.2       , 0.06666667,        inf, 0.0625    ],
       [1.        , 0.08333333, 0.14285714, 0.02222222, 0.16666667]])

In [21]:
np.random.seed(seed=101)
arr = np.random.randint(low=-10, high=25, size=(3,5))
arr

array([[ 21,   1,   7,  -4,  13],
       [  1,  -1,   3,  -6,  18],
       [-10,  -5,   2,  19,   9]])

In [22]:
np.sqrt(arr) # Square root of each element in the array

/var/folders/yn/4hm9bbfn0414pdpdfbn4x7sh0000gn/T/ipykernel_22289/1137436022.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr) # Square root of each element in the array


array([[4.58257569, 1.        , 2.64575131,        nan, 3.60555128],
       [1.        ,        nan, 1.73205081,        nan, 4.24264069],
       [       nan,        nan, 1.41421356, 4.35889894, 3.        ]])

In [23]:
np.abs(arr) # Absolute value of each element in the array

array([[21,  1,  7,  4, 13],
       [ 1,  1,  3,  6, 18],
       [10,  5,  2, 19,  9]])

In [24]:
np.exp2(arr) # 2 raised to the power of each element in the array

array([[2.097152e+06, 2.000000e+00, 1.280000e+02, 6.250000e-02,
        8.192000e+03],
       [2.000000e+00, 5.000000e-01, 8.000000e+00, 1.562500e-02,
        2.621440e+05],
       [9.765625e-04, 3.125000e-02, 4.000000e+00, 5.242880e+05,
        5.120000e+02]])

In [25]:
np.log(arr)

/var/folders/yn/4hm9bbfn0414pdpdfbn4x7sh0000gn/T/ipykernel_22289/3120950136.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([[3.04452244, 0.        , 1.94591015,        nan, 2.56494936],
       [0.        ,        nan, 1.09861229,        nan, 2.89037176],
       [       nan,        nan, 0.69314718, 2.94443898, 2.19722458]])

In [26]:
np.log2(arr) # Base 2 logarithm of each element in the array

/var/folders/yn/4hm9bbfn0414pdpdfbn4x7sh0000gn/T/ipykernel_22289/2680528797.py:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr) # Base 2 logarithm of each element in the array


array([[4.39231742, 0.        , 2.80735492,        nan, 3.70043972],
       [0.        ,        nan, 1.5849625 ,        nan, 4.169925  ],
       [       nan,        nan, 1.        , 4.24792751, 3.169925  ]])

In [27]:
np.log10(arr) # Base 10 logarithm of each element in the array

/var/folders/yn/4hm9bbfn0414pdpdfbn4x7sh0000gn/T/ipykernel_22289/3507947169.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr) # Base 10 logarithm of each element in the array


array([[1.32221929, 0.        , 0.84509804,        nan, 1.11394335],
       [0.        ,        nan, 0.47712125,        nan, 1.25527251],
       [       nan,        nan, 0.30103   , 1.2787536 , 0.95424251]])

In [28]:
np.std(arr) # Standard deviation of the array

9.344279295673667

In [29]:
np.mean(arr) # Mean of the array

4.533333333333333

In [30]:
np.median(arr) # Median of the array

2.0

In [31]:
np.max(arr) # Maximum value in the array

21

In [32]:
np.min(arr) # Minimum value in the array

-10

In [33]:
np.sum(arr) # Sum of all elements in the array

68

In [34]:
arr

array([[ 21,   1,   7,  -4,  13],
       [  1,  -1,   3,  -6,  18],
       [-10,  -5,   2,  19,   9]])

In [35]:
np.sum(arr, axis=0)  # Sum along the first axis (columns)

array([12, -5, 12,  9, 40])

In [36]:
np.sum(arr, axis=1)  # Sum along the second axis (rows)

array([38, 15, 15])

In [38]:
macro_arr = np.array([[513850, 0.4, 0.5], [516876, 0.3, 0.5], [518915, 0.4, 0.5], [521920, 0.4, 0.5], [
                     523813, 0.7, 0.5], [526750, 0.7, 0.5], [528712, 1.0, 0.25], [532082, 1.5, 0.25]])
macro_arr

array([[5.13850e+05, 4.00000e-01, 5.00000e-01],
       [5.16876e+05, 3.00000e-01, 5.00000e-01],
       [5.18915e+05, 4.00000e-01, 5.00000e-01],
       [5.21920e+05, 4.00000e-01, 5.00000e-01],
       [5.23813e+05, 7.00000e-01, 5.00000e-01],
       [5.26750e+05, 7.00000e-01, 5.00000e-01],
       [5.28712e+05, 1.00000e+00, 2.50000e-01],
       [5.32082e+05, 1.50000e+00, 2.50000e-01]])

In [41]:
macro_arr[:,0] # First column of macro_arr

array([513850., 516876., 518915., 521920., 523813., 526750., 528712.,
       532082.])

In [ ]:
np.sum(macro_arr[:4, 0]) # Sum of the first column of the first four rows

2071561.0

In [44]:
np.subtract(macro_arr[:, 2], macro_arr[:, 1]) # Subtracting the second column from the third column of macro_arr

array([ 0.1 ,  0.2 ,  0.1 ,  0.1 , -0.2 , -0.2 , -0.75, -1.25])

In [49]:
np.mean(macro_arr[:, 1:], axis=0) # Mean of the second and third columns of macro_arr

array([0.675 , 0.4375])

In [50]:
np.std(macro_arr[:, 1:], axis=0) # Standard deviation of the second and third columns of macro_arr

array([0.3799671 , 0.10825318])