In [3]:
import numpy as np

In [4]:
np.random.seed(seed=0) # set seed for reproducibility
arr = np.random.randint(low=1, high=150, size=30) # 1-d array, shape: 30 elements
arr

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89, 141,  59,  40,
        88,  89,  82,  26,  78,  73,  10, 149, 116,  80,  83, 100,  30,
       148, 148, 143,  33])

In [5]:
arr_reshaped = arr.reshape(3, 10) # reshape to 2-d array, shape: 3 x 10
arr_reshaped

array([[ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89],
       [141,  59,  40,  88,  89,  82,  26,  78,  73,  10],
       [149, 116,  80,  83, 100,  30, 148, 148, 143,  33]])

In [ ]:
arr_reshaped = arr.reshape(3, 2, 5) # reshape to 3-d array, shape: 3 x 2 x 5
arr_reshaped

array([[[ 48, 118,  68, 104,  10],
        [ 22,  37,  88,  71,  89]],

       [[141,  59,  40,  88,  89],
        [ 82,  26,  78,  73,  10]],

       [[149, 116,  80,  83, 100],
        [ 30, 148, 148, 143,  33]]])

In [8]:
arr = np.arange(start=1,stop=9,step=1)
print(f"array: \n {arr} \n\n"
      f"array shape: {arr.shape}")

array: 
 [1 2 3 4 5 6 7 8] 

array shape: (8,)


In [11]:
arr_reshaped = arr.reshape(-1,1)

# it is a 2-D array because you passed a tuple with 2 items
# the -1 means 'unknown', so you don't know how many rows this 2-D array will have
# the 1 means you want a single column

print(f"array: \n {arr_reshaped} \n\n"
      f"array shape: {arr_reshaped.shape}")

array: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 

array shape: (8, 1)


In [13]:
arr_reshaped = arr.reshape(-1,2)
print(f"array: \n {arr_reshaped} \n\n"
      f"array shape: {arr_reshaped.shape}")

array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

array shape: (4, 2)


In [14]:
np.random.seed(seed=0) # set seed for reproducibility
arr = np.random.randint(low=1, high=150, size=(2,5)) # 2-d array, shape: 2 x 5
arr

array([[ 48, 118,  68, 104,  10],
       [ 22,  37,  88,  71,  89]])

In [15]:
arr_flattened = arr.flatten() # flatten to 1-d array
arr_flattened

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89])

In [16]:
arr_reshaped = arr.reshape(-1) # reshape to 1-d array
arr_reshaped

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89])

In [21]:
arr

array([[ 48, 118,  68, 104,  10],
       [ 22,  37,  88,  71,  89]])

In [19]:
arr.min() # minimum value in the array

10

In [20]:
arr.max() # maximum value in the array

118

In [23]:
arr.argmin() # index of the minimum value in the array

4

In [24]:
arr.argmax() # index of the maximum value in the array

1

In [25]:
arr.min(axis=0) # minimum value along axis 0 (columns)

array([22, 37, 68, 71, 10])

In [26]:
arr.argmin(axis=0) # index of the minimum value along axis 0 (columns)

array([1, 1, 0, 1, 0])

In [27]:
arr.min(axis=1) # minimum value along axis 1 (rows)

array([10, 22])

In [28]:
arr.argmin(axis=1) # index of the minimum value along axis 1 (rows)

array([4, 0])

In [29]:
arr = np.arange(start=1, stop=11, step=1) # create a 1-d array with values from 1 to 10
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr = np.arange(start=1, stop=11, step=1).reshape(5,2) # create a 2-d array with values from 1 to 10, shape: 5 x 2
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
print(f"Array: \n {arr} \n\n"
      f"Array shape: {arr.shape} \n\n"
      f"Array type: {arr.dtype}")

Array: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

Array shape: (5, 2) 

Array type: int64


In [32]:
np.random.seed(seed=0)
arr = np.random.randn(2,4)
arr

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721]])

In [33]:
print(f"Array: \n {arr} \n\n"
      f"Array shape: {arr.shape} \n\n"
      f"Array type: {arr.dtype}")

Array: 
 [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]] 

Array shape: (2, 4) 

Array type: float64
