In [1]:
import numpy as np

In [2]:
arr = np.arange(start=0, stop=26, step=2) # generates 1D array
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [3]:
arr[8] # Accessing the 9th element (index 8) of the array

16

In [4]:
arr[0] # Accessing the first element (index 0) of the array

0

In [5]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [7]:
arr[1:5] # Accessing elements from index 1 to 4 (5 is exclusive) 

array([2, 4, 6, 8])

In [8]:
arr[0:5] # Slicing the first 5 elements

array([0, 2, 4, 6, 8])

In [9]:
arr[5:10] # Accessing elements from index 5 to 9 (10 is exclusive)

array([10, 12, 14, 16, 18])

In [10]:
arr[:5] # Accessing the first 5 elements (same as arr[0:5])

array([0, 2, 4, 6, 8])

In [11]:
arr[7:] # Accessing elements from index 7 to the end of the array

array([14, 16, 18, 20, 22, 24])

In [12]:
np.random.seed(seed=101) # Setting seed for reproducibility
arr = np.random.randint(low=10, high=50, size=(3,5)) # 2-D array, shape: 3 x 5
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

In [13]:
arr[1:0] 

array([], shape=(0, 5), dtype=int64)

In [14]:
arr[1,0] # Accessing the element at row 1, column 0 of the 2D array

21

In [15]:
arr[1,:] # Accessing all elements in row 1 of the 2D array

array([21, 19, 23, 14, 38])

In [16]:
arr[:,3] # Accessing all elements in column 3 of the 2D array

array([16, 14, 39])

In [17]:
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

In [18]:
arr[:2,1:] # Accessing the first 2 rows and columns from index 1 to the end of the 2D array

array([[21, 27, 16, 33],
       [19, 23, 14, 38]])

In [19]:
arr[1:,3:] # Accessing rows from index 1 to the end and columns from index 3 to the end of the 2D array

array([[14, 38],
       [39, 29]])

In [20]:
np.random.seed(seed=101) # Setting seed for reproducibility
arr = np.random.randint(low=10, high=50, size=(3, 3, 4)) # 3-D array, shape: 3 x 3 x 4
arr

array([[[41, 21, 27, 16],
        [33, 21, 19, 23],
        [14, 38, 10, 15]],

       [[22, 39, 29, 18],
        [39, 44, 18, 29],
        [20, 22, 41, 33]],

       [[10, 19, 18, 46],
        [29, 45, 38, 17],
        [20, 49, 48, 19]]])

In [ ]:
arr[1,0,0] # Accesing element at array 1, row 0, column 0 of the 3D array

22

In [22]:
arr[2,1,:] # Accessing all elements in row 1 of array 2 in the 3D array

array([29, 45, 38, 17])

In [23]:
arr[0,:,2] # Accessing all elements in column 2 of the first array in the 3D array

array([27, 19, 10])

In [24]:
arr[0,:2,:3] # Accessing the first 2 rows and first 3 columns of the first array in the 3D array

array([[41, 21, 27],
       [33, 21, 19]])

In [25]:
arr[0:2,:2,:3] # Accessing the first 2 arrays, first 2 rows, and first 3 columns in the 3D array

array([[[41, 21, 27],
        [33, 21, 19]],

       [[22, 39, 29],
        [39, 44, 18]]])

In [26]:
arr

array([[[41, 21, 27, 16],
        [33, 21, 19, 23],
        [14, 38, 10, 15]],

       [[22, 39, 29, 18],
        [39, 44, 18, 29],
        [20, 22, 41, 33]],

       [[10, 19, 18, 46],
        [29, 45, 38, 17],
        [20, 49, 48, 19]]])

In [27]:
arr[1:,:3,1:3] # Accessing rows from index 1 to the end, columns from index 1 to 3 in the 3D array

array([[[39, 29],
        [44, 18],
        [22, 41]],

       [[19, 18],
        [45, 38],
        [49, 48]]])